### ISSUE TITLE
is this project live?

### ISSUE THREAD

**Issue by vik0803** [RidaRidss/Task-Force#1]
Hello,

I was thinking to add some additional stuff like news and weather to it so want to check if this project is still on github?

thanks
vik

**Comment by RidaRidss** [comment]
yes it is @vik0803

**Comment by vik0803** [comment]
Hi @RidaRidss ,

I dont see the code available on the github so can you please upload it so that I can add those features and commit it back. 

Thanks,
Vik

**Comment by RidaRidss** [comment]
This project is confidential , so i cannot open source it , you can check other open source repo's for that :)
